# Complete AOTY Genre Hierarchy with Parent-Child Relationships
# This is the source of truth for all genres

GENRE_HIERARCHY = {
    # Genres with no subgenres
    "Ambient Pop": [],
    "ASMR": [],
    "Christmas": [],
    "Epic Collage": [],
    "Glitch Pop": [],
    "Hymns": [],
    "Hypnagogic Pop": [],
    "Mashup": [],
    "Musical Parody": [],
    "Polka": [],
    "Sampledelia": [],
    "Standards": [],
    "Totalism": [],
    "Toypop": [],
    
    # Genres with subgenres
    "Ambient": [
        "Ambient Dub",
        "Ambient Noise Wall",
        "Black Ambient",
        "Dark Ambient",
        "Ritual Ambient",
        "Space Ambient",
        "Tribal Ambient"
    ],
    "Blues": [
        "Acoustic Chicago Blues",
        "Boogie-Woogie",
        "British Blues",
        "Chicago Blues",
        "Country Blues",
        "Delta Blues",
        "Electric Blues",
        "Electric Texas Blues",
        "Jump Blues",
        "New Orleans Blues",
        "Piano Blues",
        "Piedmont Blues",
        "Soul Blues",
        "Swamp Blues",
        "Vaudeville Blues"
    ],
    "CCM": [
        "Christian Hip Hop",
        "Christian Rock",
        "Praise & Worship",
        "Urban Contemporary Gospel"
    ],
    "Chanson": [
        "Chanson à texte",
        "Chanson Québécoise",
        "Nouvelle Chanson Française"
    ],
    "Children's Music": [
        "Fairy Tales",
        "Lullabies"
    ],
    "Classical": [
        "Andalusian Classical Music",
        "Ballet",
        "Baroque Music",
        "Carnatic Classical Music",
        "Chamber Music",
        "Chinese Classical Music",
        "Choral",
        "Cinematic Classical",
        "Classical Period",
        "East Asian Classical Music",
        "Epic Music",
        "Grand Opéra",
        "Hindustani Classical Music",
        "Holy Minimalism",
        "Impressionism",
        "Japanese Classical Music",
        "Jeong-Ak",
        "Korean Classical Music",
        "Light Music",
        "Middle Eastern Classical Music",
        "Minimalism",
        "Minyue",
        "Modern Classical",
        "Musique Concrète Instrumentale",
        "Nagauta",
        "Neoclassicism",
        "Nocturne",
        "Oratorio",
        "Orchestral",
        "Post-Minimalism",
        "Renaissance Music",
        "Romanticism",
        "Singspiel",
        "Spectralism",
        "Symphony",
        "Sōkyoku",
        "Tone Poem",
        "Western Classical Music"
    ],
    "Comedy": [
        "Break-In",
        "Comedy Rap",
        "Comedy Rock",
        "Dutch Cabaret",
        "Kabarett",
        "Prank Calls",
        "Sketch Comedy",
        "Stand-Up Comedy"
    ],
    "Country": [
        "Alt-Country",
        "Bakersfield Sound",
        "Bluegrass",
        "Bluegrass Gospel",
        "Bro-Country",
        "Contemporary Country",
        "Country Gospel",
        "Country Pop",
        "Country Rock",
        "Country Soul",
        "Countrypolitan",
        "Gothic Country",
        "Honky Tonk",
        "Jamgrass",
        "Nashville Sound",
        "Neo-Traditionalist Country",
        "Old-Time",
        "Outlaw Country",
        "Progressive Country",
        "Traditional Country",
        "Truck Driving Country",
        "Urban Cowboy"
    ],
    "Dance": [
        "Acid Breaks",
        "Acid Trance",
        "Acidcore",
        "Afro House",
        "Aggrotech",
        "Alternative Dance",
        "Artcore",
        "Bass House",
        "Bassline",
        "Belgian Techno",
        "Birmingham Sound",
        "Bleep Techno",
        "Bouncy Techno",
        "Brazilian Bass",
        "Breakbeat",
        "Breakcore",
        "Briddim",
        "Brostep",
        "Bubblegum Dance",
        "Changa Tuki",
        "Chicago Hard House",
        "Chillstep",
        "Colour Bass",
        "Coupé-Décalé",
        "Crossbreed",
        "Dance-Pop",
        "Dancefloor Drum and Bass",
        "Dariacore",
        "Dark Electro",
        "Dark Psytrance",
        "Darkside",
        "Darkstep",
        "Deathchant Hardcore",
        "Deathstep",
        "Disco",
        "Disco polo",
        "Diva House",
        "Doomcore",
        "Dream Trance",
        "Drum and Bass",
        "Drumfunk",
        "Dubstep",
        "Dungeon Sound",
        "Dutch House",
        "East Coast Club",
        "Electro House",
        "Electro Latino",
        "Electro-Disco",
        "Electronic Dance Music",
        "Euphoric Hardstyle",
        "Euro-Disco",
        "Eurodance",
        "Florida Breaks",
        "Footwork",
        "Footwork Jungle",
        "Forest Psytrance",
        "French Electro",
        "French House",
        "Full-On Psytrance",
        "Funk Mandelão",
        "Funk Melody",
        "Funkot",
        "Future Bounce",
        "Future House",
        "Future Rave",
        "Future Riddim",
        "G-House",
        "Ghetto House",
        "Glitch Hop [EDM]",
        "Grebo",
        "Grime",
        "Happy Hardcore",
        "Hard Dance",
        "Hard Techno",
        "Hardbag",
        "Hardbass",
        "Hardcore [EDM]",
        "Hardgroove Techno",
        "Hardstep",
        "Hardstyle",
        "Hardtek",
        "Hardwave",
        "Heaven Trap",
        "Hi-Tech Psytrance",
        "House",
        "Ibiza Trance",
        "Italo Dance",
        "Italo-Disco",
        "Jersey Club",
        "Juke",
        "Jumpstyle",
        "Jungle",
        "Jungle Terror",
        "Latin Disco",
        "Liquid Drum and Bass",
        "Lo-Fi House",
        "Makina",
        "Melbourne Bounce",
        "Melodic Bass",
        "Melodic House",
        "Midtempo Bass",
        "Minatory",
        "Minimal Drum and Bass",
        "Moombahcore",
        "Moombahton",
        "Mutant Disco",
        "Neo-Grime",
        "Neurohop",
        "New Rave",
        "Nitzhonot",
        "NRG",
        "Nu Skool Breaks",
        "Organic House",
        "Philly Club",
        "Phonk House",
        "Progressive Breaks",
        "Progressive Psytrance",
        "Psycore",
        "Psystyle",
        "Psytrance",
        "Purple Sound",
        "Ragga Jungle",
        "Raggacore",
        "Rawphoric",
        "Rawstyle",
        "Red Disco",
        "Riddim",
        "Ritmada",
        "Romanian Popcorn",
        "Schranz",
        "Scouse House",
        "Skullstep",
        "Skweee",
        "Space Disco",
        "Spacesynth",
        "Speed House",
        "Suomisaundi",
        "Tearout",
        "Tearout [Brostep]",
        "Techno",
        "Techno Bass",
        "Techstep",
        "Tecnorumba",
        "Terrorcore",
        "Township Bubblegum",
        "Trance",
        "Trancestep",
        "Trap [EDM]",
        "UK Hard House",
        "Wonky Techno"
    ],
    "Darkwave": [
        "Ethereal Wave",
        "Neoclassical Darkwave"
    ],
    "Easy Listening": [
        "Cocktail Nation",
        "Exotica",
        "Light Music",
        "Lounge",
        "Space Age Pop"
    ],
    "Electronic": [
        "2-Step",
        "Acid Breaks",
        "Acid House",
        "Acid Jazz",
        "Acid Techno",
        "Acid Trance",
        "Acidcore",
        "Afro House",
        "Aggrotech",
        "Amapiano",
        "Ambient Dub",
        "Ambient House",
        "Ambient Techno",
        "Ambient Trance",
        "Artcore",
        "Balearic Beat",
        "Ballroom",
        "Baltimore Club",
        "Barber Beats",
        "Bass House",
        "Bassline",
        "Batida",
        "Belgian Techno",
        "Berlin School",
        "Big Beat",
        "Big Room House",
        "Big Room Trance",
        "Binaural Beats",
        "Birmingham Sound",
        "Bit Music",
        "Bitpop",
        "Bleep Techno",
        "Bouncy Techno",
        "Brazilian Bass",
        "Brazilian Phonk",
        "Breakbeat",
        "Breakbeat Hardcore",
        "Breakcore",
        "Breakstep",
        "Briddim",
        "Broken Beat",
        "Brostep",
        "Bubblegum Bass",
        "Changa Tuki",
        "Chicago Hard House",
        "Chicago House",
        "Chillout",
        "Chillstep",
        "Chillsynth",
        "Chillwave",
        "Colour Bass",
        "Comfy Synth",
        "Complextro",
        "Coupé-Décalé",
        "Crossbreed",
        "Dancefloor Drum and Bass",
        "Dariacore",
        "Dark Ambient",
        "Dark Electro",
        "Dark Psytrance",
        "Darkside",
        "Darkstep",
        "Darksynth",
        "Death Industrial",
        "Deathchant Hardcore",
        "Deathstep",
        "Deconstructed Club",
        "Deep House",
        "Deep Tech",
        "Detroit Techno",
        "Digital Fusion",
        "Diva House",
        "Doomcore",
        "Downtempo",
        "Dream Trance",
        "Drift Phonk",
        "Drill and Bass",
        "Drum and Bass",
        "Drumfunk",
        "Dub Techno",
        "Dubstep",
        "Dungeon Sound",
        "Dungeon Synth",
        "Dutch House",
        "East Coast Club",
        "EBM",
        "Eccojams",
        "Electro",
        "Electro Hop",
        "Electro House",
        "Electro Latino",
        "Electro Swing",
        "Electro-Disco",
        "Electro-Industrial",
        "Electroacoustic",
        "Electroclash",
        "Electronic Dance Music",
        "Euphoric Hardstyle",
        "Euro-Trance",
        "Eurodance",
        "Extratone",
        "Festival Progressive House",
        "Fidget House",
        "Flashcore",
        "Florida Breaks",
        "Folktronica",
        "Footwork",
        "Footwork Jungle",
        "Forest Psytrance",
        "Freeform Hardcore",
        "Freestyle",
        "Freetekno",
        "French Electro",
        "French House",
        "Frenchcore",
        "Full-On Psytrance",
        "Funk Mandelão",
        "Funkot",
        "Funky House",
        "Future Bass",
        "Future Bounce",
        "Future Garage",
        "Future House",
        "Future Rave",
        "Future Riddim",
        "Futurepop",
        "G-House",
        "Gabber",
        "Ghetto House",
        "Ghettotech",
        "Glitch",
        "Glitch Hop",
        "Glitch Hop [EDM]",
        "Gqom",
        "Grime",
        "Halftime",
        "Happy Hardcore",
        "Hard Dance",
        "Hard Drum",
        "Hard Techno",
        "Hard Trance",
        "Hardbag",
        "Hardbass",
        "Hardcore Breaks",
        "Hardcore [EDM]",
        "Hardgroove Techno",
        "Hardstep",
        "Hardstyle",
        "Hardtek",
        "Hardvapour",
        "Hardwave",
        "Heaven Trap",
        "HexD",
        "Hi-NRG",
        "Hi-Tech Psytrance",
        "Horror Synth",
        "House",
        "Hybrid Trap",
        "Hyperpop",
        "Ibiza Trance",
        "IDM",
        "Illbient",
        "Indietronica",
        "Industrial Techno",
        "Italo Dance",
        "Italo-Disco",
        "J-core",
        "Jazzstep",
        "Jersey Club",
        "Juke",
        "Jump-Up",
        "Jumpstyle",
        "Jungle",
        "Jungle Terror",
        "Kawaii Future Bass",
        "Kuduro",
        "Latin Electronic",
        "Liquid Drum and Bass",
        "Livetronica",
        "Lo-Fi House",
        "Lolicore",
        "Makina",
        "Melbourne Bounce",
        "Melodic Bass",
        "Melodic House",
        "Melodic Techno",
        "Microhouse",
        "Microsound",
        "Midtempo Bass",
        "Minatory",
        "Minimal Drum and Bass",
        "Minimal Synth",
        "Minimal Techno",
        "Minimal Wave",
        "Moogsploitation",
        "Moombahcore",
        "Moombahton",
        "Musique Concrète",
        "Neo-Grime",
        "Nerdcore Techno",
        "Neurofunk",
        "Neurohop",
        "New Beat",
        "Nightcore",
        "Nitzhonot",
        "NRG",
        "Nu Jazz",
        "Nu Skool Breaks",
        "Nu-Disco",
        "Organic House",
        "Outsider House",
        "Peak Time Techno",
        "Philly Club",
        "Phonk House",
        "Power Electronics",
        "Progressive Breaks",
        "Progressive Electronic",
        "Progressive House",
        "Progressive Psytrance",
        "Psybient",
        "Psycore",
        "Psystyle",
        "Psytrance",
        "Purple Sound",
        "Ragga Jungle",
        "Raggacore",
        "Rawphoric",
        "Rawstyle",
        "Red Disco",
        "Riddim",
        "Ritmada",
        "Romanian Popcorn",
        "Rominimal",
        "Schranz",
        "Scouse House",
        "Sequencer & Tracker",
        "Skullstep",
        "Skweee",
        "Slap House",
        "Space Disco",
        "Spacesynth",
        "Speed Garage",
        "Speed House",
        "Speedcore",
        "Splittercore",
        "Suomisaundi",
        "Synth Punk",
        "Synthpop",
        "Synthwave",
        "Tearout",
        "Tearout [Brostep]",
        "Tech House",
        "Tech Trance",
        "Techno",
        "Techno Bass",
        "Techstep",
        "Tecnobrega",
        "Tecnorumba",
        "Terrorcore",
        "Trance",
        "Trancestep",
        "Trap [EDM]",
        "Tribal House",
        "Trip Hop",
        "Tropical House",
        "Turntablism",
        "Twerk",
        "UK Bass",
        "UK Funky",
        "UK Garage",
        "UK Hard House",
        "Uplifting Trance",
        "Uptempo Hardcore",
        "Utopian Virtual",
        "Vaportrap",
        "Vaporwave",
        "Wave",
        "Weightless",
        "Winter Synth",
        "Witch House",
        "Wonky",
        "Wonky Techno"
    ],
    "Experimental": [
        "Conducted Improvisation",
        "Data Sonification",
        "Death Industrial",
        "Drone",
        "Electroacoustic",
        "Free Improvisation",
        "Hauntology",
        "Indeterminacy",
        "Lowercase",
        "Microsound",
        "Modern Creative",
        "Musique Concrète",
        "Musique Concrète Instrumentale",
        "Noise",
        "Onkyo",
        "Plunderphonics",
        "Power Electronics",
        "Reductionism",
        "Sound Art",
        "Sound Collage",
        "Sound Poetry",
        "Tape Music",
        "Turntable Music"
    ],
    "Field Recordings": [
        "Animal Sounds",
        "Birdsong",
        "Nature Recordings",
        "Radio Broadcast Recordings"
    ],
    "Flamenco": [
        "Flamenco Jazz",
        "Flamenco Nuevo"
    ],
    "Folk": [
        "American Folk Music",
        "American Primitivism",
        "Anti-Folk",
        "Appalachian Folk Music",
        "Avant-Folk",
        "Balkan Brass Band",
        "Candombe",
        "Celtic Folk",
        "Chamber Folk",
        "Contemporary Folk",
        "Dark Folk",
        "Folk Pop",
        "Folk Punk",
        "Folk Rock",
        "Freak Folk",
        "Greek Folk Music",
        "Indie Folk",
        "Irish Folk Music",
        "Israeli Folk Music",
        "Joropo",
        "Jug Band",
        "Korean Folk Music",
        "Kurdish Folk",
        "Laïko",
        "Lithuanian Folk Music",
        "Middle Eastern Folk",
        "Musette",
        "Muzică Lăutărească",
        "Neo-Medieval Folk",
        "Neofolk",
        "Psychedelic Folk",
        "Rembetika",
        "Rock Rural",
        "Sea Shanties",
        "Stomp and Holler",
        "Traditional Folk Music"
    ],
    "Funk": [
        "Afro-Funk",
        "Britfunk",
        "Go-Go",
        "Jazz-Funk",
        "Minneapolis Sound",
        "P-Funk",
        "Synth Funk"
    ],
    "Gamelan": [
        "Balinese Gamelan"
    ],
    "Gospel": [
        "Bluegrass Gospel",
        "Country Gospel",
        "Southern Gospel",
        "Urban Contemporary Gospel"
    ],
    "Hip Hop": [
        "Abstract Hip Hop",
        "Afro Trap",
        "Afroswing",
        "Ambient Plugg",
        "Asian Rock",
        "Atlanta Bass",
        "Boom Bap",
        "Bop",
        "Bounce",
        "Britcore",
        "Chicago Drill",
        "Chicano Rap",
        "Chipmunk Soul",
        "Chopped and Screwed",
        "Christian Hip Hop",
        "Cloud Rap",
        "Comedy Rap",
        "Conscious Hip Hop",
        "Country Rap",
        "Crunk",
        "Dark Plugg",
        "Detroit Trap",
        "Digicore",
        "Dirty South",
        "Disco Rap",
        "Drill",
        "Drumless",
        "Dungeon Rap",
        "East Coast Hip Hop",
        "Emo Rap",
        "Experimental Hip Hop",
        "Free Car Music",
        "French Hip Hop",
        "Futuristic Swag",
        "G-Funk",
        "Gangsta Rap",
        "Genge",
        "Hardcore Hip Hop",
        "Hyphy",
        "Industrial Hip Hop",
        "Instrumental Hip Hop",
        "Japanese Hip Hop",
        "Jazz Rap",
        "Jerk",
        "Jerk Rap",
        "Jersey Club Rap",
        "Jersey Drill",
        "Jook",
        "Latin Rap",
        "Lo-Fi Hip Hop",
        "Lowend",
        "Memphis Rap",
        "Miami Bass",
        "Mid-School Hip Hop",
        "Mobb Music",
        "Nerdcore Hip Hop",
        "Nervous Music",
        "New Jazz",
        "New York Drill",
        "No Melody",
        "Phonk",
        "Plugg",
        "Political Hip Hop",
        "Pop Rap",
        "Rage",
        "Rare Phonk",
        "Ratchet Music",
        "Regalia",
        "Sexy Drill",
        "Snap",
        "Southern Hip Hop",
        "Tamborzão",
        "Techno Bass",
        "Terror Plugg",
        "Trap",
        "Trap Latino",
        "Trap Soul",
        "Tread",
        "UK Drill",
        "UK Hip Hop",
        "West Coast Hip Hop"
    ],
    "Industrial": [
        "Birmingham Sound",
        "Cyber Metal",
        "Death Industrial",
        "Industrial Metal",
        "Industrial Rock",
        "Industrial Techno",
        "Martial Industrial",
        "Post-Industrial",
        "Power Electronics"
    ],
    "Jazz": [
        "Afro-Cuban Jazz",
        "Afro-Jazz",
        "Arabic Jazz",
        "Avant-Garde Jazz",
        "Bebop",
        "Big Band",
        "British Dance Band",
        "Cape Jazz",
        "Chamber Jazz",
        "Cool Jazz",
        "Crime Jazz",
        "Dark Jazz",
        "Dixieland",
        "ECM Style Jazz",
        "Ethio-Jazz",
        "European Free Jazz",
        "Flamenco Jazz",
        "Free Jazz",
        "Hard Bop",
        "Indo Jazz",
        "Jazz Fusion",
        "Jazz manouche",
        "Jazz Poetry",
        "Jazz-Funk",
        "Latin Jazz",
        "Marabi",
        "Mbaqanga",
        "Modal Jazz",
        "Post-Bop",
        "Progressive Big Band",
        "Samba-Jazz",
        "Smooth Jazz",
        "Soul Jazz",
        "Spiritual Jazz",
        "Spy Music",
        "Stride",
        "Swing",
        "Swing Revival",
        "Third Stream",
        "Vocal Jazz",
        "Yass"
    ],
    "Marching Band": [
        "Pipe Band"
    ],
    "Metal": [
        "Alternative Metal",
        "Atmospheric Black Metal",
        "Atmospheric Sludge Metal",
        "Avant-Garde Metal",
        "Black Metal",
        "Blackened Death Metal",
        "Blackgaze",
        "Brutal Death Metal",
        "Celtic Metal",
        "Cyber Metal",
        "Cybergrind",
        "Death 'n' Roll",
        "Death Doom Metal",
        "Death Metal",
        "Deathcore",
        "Depressive Black Metal",
        "Dissonant Black Metal",
        "Dissonant Death Metal",
        "Djent",
        "Doom Metal",
        "Doomgaze",
        "Downtempo Deathcore",
        "Drone Metal",
        "Epic Doom Metal",
        "Folk Metal",
        "Funeral Doom Metal",
        "Funk Metal",
        "Glam Metal",
        "Gothic Metal",
        "Grindcore",
        "Groove Metal",
        "Heavy Metal",
        "Industrial Metal",
        "Kawaii Metal",
        "Melodic Black Metal",
        "Melodic Death Metal",
        "Melodic Metalcore",
        "Metalcore",
        "Mittelalter-Metal",
        "Neoclassical Metal",
        "Neue Deutsche Härte",
        "Noisegrind",
        "Nu Metal",
        "NWOBHM",
        "Pagan Black Metal",
        "Pagan Metal",
        "Pornogrind",
        "Post-Black Metal",
        "Post-Metal",
        "Power Metal",
        "Progressive Death Metal",
        "Progressive Metal",
        "Rap Metal",
        "Raw Black Metal",
        "Slam Death Metal",
        "Sludge Metal",
        "Southern Metal",
        "Speed Metal",
        "Stoner Metal",
        "Symphonic Black Metal",
        "Symphonic Metal",
        "Technical Death Metal",
        "Technical Thrash Metal",
        "Thall",
        "Thrash Metal",
        "Traditional Doom Metal",
        "Trance Metal",
        "US Power Metal",
        "Viking Metal",
        "War Metal"
    ],
    "MPB": [
        "Tropicália"
    ],
    "Musical Theatre & Entertainment": [
        "Cabaret",
        "Cuplé",
        "Kabarett",
        "Revue",
        "Show Tunes",
        "Singspiel",
        "Vaudeville"
    ],
    "New Age": [
        "Neoclassical New Age"
    ],
    "Pop": [
        "Adult Contemporary",
        "Afrobeats",
        "Akishibu-kei",
        "Alt-Pop",
        "Arabic Pop",
        "Art Pop",
        "Balkan Pop-Folk",
        "Baroque Pop",
        "Big Music",
        "Boy Band",
        "Brill Building",
        "Britpop",
        "Bubblegum Pop",
        "C-Pop",
        "Canción Melódica",
        "Cantopop",
        "City Pop",
        "Classical Crossover",
        "Country Pop",
        "Countrypolitan",
        "Cuddlecore",
        "Dance-Pop",
        "Dansbandsmusik",
        "Denpa",
        "Disco polo",
        "Electropop",
        "Europop",
        "Flamenco Pop",
        "Folk Pop",
        "French Pop",
        "Funk Melody",
        "Futurepop",
        "Girl Group",
        "Group Sounds",
        "Hyperpop",
        "Indie Pop",
        "Italo Pop",
        "J-Pop",
        "Jazz Pop",
        "Jovem Guarda",
        "K-Pop",
        "Kayōkyoku",
        "Korean Ballad",
        "Latin Pop",
        "Mood Kayō",
        "Nederpop",
        "OPM",
        "Piano Rock",
        "Picopop",
        "Pop Raï",
        "Pop Rock",
        "Power Pop",
        "Progressive Pop",
        "Romanian Popcorn",
        "Rumba catalana",
        "Russian Chanson",
        "Schlager",
        "Sertanejo Romântico",
        "Shibuya-kei",
        "Sophisti-Pop",
        "Soviet Estrada",
        "Stereo",
        "Stomp and Holler",
        "Sunshine Pop",
        "Synthpop",
        "Techno Kayō",
        "Tecnorumba",
        "Teen Pop",
        "Township Bubblegum",
        "Traditional Pop",
        "Tropical Rock",
        "Turkish Pop",
        "Twee Pop",
        "V-Pop",
        "Vocal Surf",
        "Yakousei",
        "Yé-yé"
    ],
    "Psychedelia": [
        "Heavy Psych",
        "Neo-Psychedelia",
        "Paisley Underground",
        "Psichedelia occulta italiana",
        "Psychedelic Folk",
        "Psychedelic Pop",
        "Psychedelic Rock",
        "Psychedelic Soul",
        "Raga Rock",
        "Zamrock"
    ],
    "Punk": [
        "Anarcho-Punk",
        "Art Punk",
        "Beatdown Hardcore",
        "Blackened Crust",
        "Burning Spirits",
        "Celtic Punk",
        "Cowpunk",
        "Crust Punk",
        "D-Beat",
        "Dance-Punk",
        "Digital Hardcore",
        "Downtempo Deathcore",
        "Easycore",
        "Egg Punk",
        "Emo",
        "Emo-Pop",
        "Emocore",
        "Emoviolence",
        "Folk Punk",
        "Glam Punk",
        "Grindcore",
        "Hardcore Punk",
        "Horror Punk",
        "Mall Screamo",
        "Melodic Hardcore",
        "Metalcore",
        "Midwest Emo",
        "Neocrust",
        "Nintendocore",
        "Noisegrind",
        "Oi!",
        "Pop Punk",
        "Post-Hardcore",
        "Post-Punk",
        "Proto-Punk",
        "Psychobilly",
        "Punk Blues",
        "Punk Rock",
        "Queercore",
        "Riot Grrrl",
        "Screamo",
        "Ska Punk",
        "Skacore",
        "Skate Punk",
        "Surf Punk",
        "Swancore",
        "Synth Punk",
        "Trancecore",
        "Vikingarock"
    ],
    "R&B": [
        "Alternative R&B",
        "Blue-Eyed Soul",
        "Boogie",
        "British Rhythm & Blues",
        "Contemporary R&B",
        "Doo-Wop",
        "Hip Hop Soul",
        "Neo-Soul",
        "New Jack Swing",
        "New Orleans R&B",
        "Pop Soul",
        "Progressive Soul",
        "Rhythm and Blues",
        "Smooth Soul",
        "Soul",
        "Soul Blues",
        "Southern Soul",
        "Trap Soul",
        "Twist",
        "UK Street Soul"
    ],
    "Ragtime": [
        "Stride"
    ],
    "Reggae": [
        "Dancehall",
        "Deejay",
        "Dub",
        "Pop Reggae",
        "Roots Reggae"
    ],
    "Regional": [
        "Afro-Jazz",
        "Afrobeat",
        "Americana",
        "Andalusian Classical Music",
        "Arabesk",
        "Arabic Jazz",
        "Arabic Pop",
        "Arrocha",
        "Avtorskaya pesnya",
        "Axé",
        "Bachata",
        "Baião",
        "Balkan Brass Band",
        "Banda Sinaloense",
        "Bolero",
        "Bossa Nova",
        "Brega",
        "Brega calypso",
        "British Folk Rock",
        "Cajun Music",
        "Calypso",
        "Canción Melódica",
        "Candombe",
        "Canzone D'autore",
        "Cape Jazz",
        "Celtic Metal",
        "Chachachá",
        "Chalga",
        "Changa Tuki",
        "Chimurenga",
        "Chinese Classical Music",
        "Chinese Opera",
        "Choro",
        "Christian Liturgical Music",
        "Corrido",
        "Coupé-Décalé",
        "Cumbia",
        "Cumbia Argentina",
        "Cumbia Colombiana",
        "Cumbia Mexicana",
        "Cumbia Peruana",
        "Cuplé",
        "Dabke",
        "Dancehall",
        "Dembow",
        "Disco polo",
        "Dutch Cabaret",
        "Electric Texas Blues",
        "Electro Latino",
        "Eleki",
        "Enka",
        "Euskal Kantagintza Berria",
        "Fado",
        "Fado de Coimbra",
        "Flamenco Pop",
        "Forró",
        "Forró eletrônico",
        "Frevo",
        "Fuji",
        "Funk Brasileiro",
        "Funk Carioca",
        "Funk Melody",
        "Ghazal",
        "Gnawa",
        "Grand Opéra",
        "Gregorian Chant",
        "Highlife",
        "Huayno",
        "Hyang-Ak",
        "Indo Jazz",
        "Irish Folk Music",
        "Israeli Folk Music",
        "Japanese Folk Music",
        "Jùjú",
        "Jeong-Ak",
        "Jewish Music",
        "Jongo",
        "Joropo",
        "Kabarett",
        "Kizomba",
        "Kleinkunst",
        "Korean Classical Music",
        "Kurdish Folk",
        "Kwaito",
        "Latin American Music",
        "Latin Disco",
        "Latin Electronic",
        "Latin Soul",
        "Levenslied",
        "Lied",
        "Liedermacher",
        "Lithuanian Folk Music",
        "Mambo",
        "Mande Music",
        "Manele",
        "Manguebeat",
        "Manila Sound",
        "Marabi",
        "Maracatu",
        "Marchinha",
        "Mariachi",
        "Mbaqanga",
        "Merengue",
        "Middle Eastern Folk",
        "Milonga",
        "Minyue",
        "Minyō",
        "Mittelalter-Rock",
        "Moda de viola",
        "Modern Laika",
        "Moroccan Chaabi",
        "Musette",
        "Musica De Intervençao",
        "Muzică De Mahala",
        "Muzică Lăutărească",
        "Muzika Mizrahit",
        "Neo-Medieval Folk",
        "Nordic Folk Rock",
        "Norteño",
        "Nova Cançó",
        "Peking Opera",
        "Pimba",
        "Piseiro",
        "Plainsong",
        "Poezja śpiewana",
        "Pop Raï",
        "Portuguese Folk Music",
        "Psichedelia occulta italiana",
        "Raï",
        "Ranchera",
        "Ritmada",
        "Rock Andaluz",
        "Rock Andino",
        "Rock Rural",
        "Rocksteady",
        "Rumba catalana",
        "Russian Chanson",
        "Salsa",
        "Salsa Dura",
        "Samba",
        "Samba-Canção",
        "Samba-Choro",
        "Samba-Reggae",
        "Schlager",
        "Sephardic Music",
        "Sertanejo",
        "Sertanejo de raiz",
        "Sertanejo Romântico",
        "Sertanejo Universitário",
        "Shidaiqu",
        "Sierreño",
        "Singspiel",
        "Son Cubano",
        "Soukous",
        "Stereo",
        "Sōkyoku",
        "Tamborzão",
        "Tango",
        "Tecnobrega",
        "Tecnorumba",
        "Tejano Music",
        "Tex-Mex",
        "Tishoumaren",
        "Tizita",
        "Township Bubblegum",
        "Tropicanibalismo",
        "Turbo-Folk",
        "Turkish Pop",
        "Vallenato",
        "Vanguarda Paulista",
        "Volkstümliche Musik",
        "Waltz",
        "Xote",
        "Yiddish Folksong",
        "Zamba",
        "Zamrock"
    ],
    "Rock": [
        "Acid Rock",
        "Acoustic Rock",
        "Alternative Dance",
        "Alternative Rock",
        "Anatolian Rock",
        "AOR",
        "Art Rock",
        "Baggy",
        "Bard Rock",
        "Big Music",
        "Blues Rock",
        "Boogie Rock",
        "British Folk Rock",
        "British Rhythm & Blues",
        "Britpop",
        "Brutal Prog",
        "C86",
        "Celtic Rock",
        "Christian Rock",
        "Country Rock",
        "Cowpunk",
        "Cuddlecore",
        "Dance-Punk",
        "Dark Cabaret",
        "Deathrock",
        "Dream Pop",
        "Dunedin Sound",
        "Egg Punk",
        "Eleki",
        "Emo",
        "Experimental Rock",
        "Folk Rock",
        "Freakbeat",
        "Funk Rock",
        "Garage Rock",
        "Garage Rock Revival",
        "Geek Rock",
        "Glam Punk",
        "Glam Rock",
        "Gothic Rock",
        "Grebo",
        "Group Sounds",
        "Hard Rock",
        "Heartland Rock",
        "Indie Rock",
        "Indie Surf",
        "Industrial Rock",
        "J-Rock",
        "Jam Band",
        "Jamgrass",
        "Jangle Pop",
        "Jazz-Rock",
        "Jovem Guarda",
        "Krautrock",
        "Latin Rock",
        "Livetronica",
        "Mall Screamo",
        "Manguebeat",
        "Math Pop",
        "Math Rock",
        "Midwest Emo",
        "Mittelalter-Rock",
        "Neo-Prog",
        "Neue Deutsche Welle",
        "New Rave",
        "New Wave",
        "Noise Pop",
        "Noise Rock",
        "Nordic Folk Rock",
        "Paisley Underground",
        "Piano Rock",
        "Pop Rock",
        "Post-Punk",
        "Post-Rock",
        "Power Pop",
        "Progressive Rock",
        "Psychedelic Rock",
        "Psychobilly",
        "Pub Rock",
        "Punk Blues",
        "Punk Rock",
        "Queercore",
        "Raga Rock",
        "Rap Rock",
        "Rautalanka",
        "Rock & Roll",
        "Rock Andaluz",
        "Rock Andino",
        "Rock Opera",
        "Rock Rural",
        "Rockabilly",
        "Roots Rock",
        "Shoegaze",
        "Ska Punk",
        "Skacore",
        "Slacker Rock",
        "Soft Rock",
        "Southern Rock",
        "Space Rock",
        "Space Rock Revival",
        "Stereo",
        "Stoner Rock",
        "Surf Rock",
        "Swamp Rock",
        "Symphonic Rock",
        "Tex-Mex",
        "Tropical Rock",
        "Twee Pop",
        "Vikingarock",
        "Visual kei",
        "Vocal Surf",
        "Yacht Rock",
        "Zamrock",
        "Zolo"
    ],
    "Singer-Songwriter": [
        "Avtorskaya pesnya",
        "Canzone D'autore",
        "Chanson à texte",
        "Euskal Kantagintza Berria",
        "Kleinkunst",
        "Liedermacher",
        "Musica De Intervençao",
        "Nova Cançó",
        "Poezja śpiewana"
    ],
    "Ska": [
        "2 Tone",
        "New Tone",
        "Rocksteady",
        "Ska Punk",
        "Third Wave Ska"
    ],
    "Sound Effects": [
        "Battle Record",
        "Binaural Beats",
        "Broadband Noise"
    ],
    "Spoken Word": [
        "Beat Poetry",
        "Fairy Tales",
        "Guided Meditation",
        "Interview",
        "Jazz Poetry",
        "Lectures",
        "Poetry",
        "Radio Drama",
        "Speeches",
        "Stand-Up Comedy"
    ],
    "Vapor": [
        "Barber Beats",
        "Dreampunk",
        "Eccojams",
        "Hardvapour",
        "Utopian Virtual",
        "Vapornoise",
        "Vaportrap",
        "Vaporwave"
    ]
}

def get_all_genres():
    """Get all genres (both parent and child)"""
    all_genres = set(GENRE_HIERARCHY.keys())
    for children in GENRE_HIERARCHY.values():
        all_genres.update(children)
    return sorted(list(all_genres))

def get_parent_genres():
    """Get only parent genres"""
    return sorted(list(GENRE_HIERARCHY.keys()))

def get_child_genres(parent):
    """Get child genres for a parent genre"""
    return GENRE_HIERARCHY.get(parent, [])

def get_genre_with_children(parent):
    """Get parent genre with its children"""
    children = GENRE_HIERARCHY.get(parent, [])
    return {
        "parent": parent,
        "children": children,
        "has_children": len(children) > 0
    }
